In [1]:
# Import our dependencies
import pandas as pd

In [2]:
# Read in our data
census_df = pd.read_csv("../Resources/data/2018_data.csv")
census_df

,GEO_ID,NAME,S2506_C01_001E,S2506_C01_001M,S2506_C02_001E,S2506_C02_001M,S2506_C01_002E,S2506_C01_002M,S2506_C02_002E,S2506_C02_002M,...,S2506_C02_063E,S2506_C02_063M,S2506_C01_064E,S2506_C01_064M,S2506_C02_064E,S2506_C02_064M,S2506_C01_065E,S2506_C01_065M,S2506_C02_065E,S2506_C02_065M
0,id,Geographic Area Name,Estimate!!Owner-occupied housing units with a ...,Margin of Error!!Owner-occupied housing units ...,Estimate!!Percent owner-occupied housing units...,Margin of Error!!Percent owner-occupied housin...,Estimate!!Owner-occupied housing units with a ...,Margin of Error!!Owner-occupied housing units ...,Estimate!!Percent owner-occupied housing units...,Margin of Error!!Percent owner-occupied housin...,...,Estimate!!Percent owner-occupied housing units...,Margin of Error!!Percent owner-occupied housin...,Estimate!!Owner-occupied housing units with a ...,Margin of Error!!Owner-occupied housing units ...,Estimate!!Percent owner-occupied housing units...,Margin of Error!!Percent owner-occupied housin...,Estimate!!Owner-occupied housing units with a ...,Margin of Error!!Owner-occupied housing units ...,Estimate!!Percent owner-occupied housing units...,Margin of Error!!Percent owner-occupied housin...
1,0400000US02,Alaska,102706,3651,102706,3651,1301,556,1.3,0.5,...,78.4,1.8,8876,1265,8.6,1.1,3590,121,3590,121
2,0400000US23,Maine,247344,5145,247344,5145,8347,1303,3.4,0.5,...,80.3,1.3,1233,463,0.5,0.2,2714,47,2714,47
3,0400000US37,North Carolina,1623735,15836,1623735,15836,46822,3291,2.9,0.2,...,53.2,0.6,23669,2183,1.5,0.1,1625,18,1625,18
4,0400000US29,Missouri,986408,11918,986408,11918,48211,2855,4.9,0.3,...,55.1,0.7,14455,1968,1.5,0.2,1710,25,1710,25
5,0400000US42,Pennsylvania,2076151,16310,2076151,16310,69616,3687,3.4,0.2,...,79.0,0.4,19594,2070,0.9,0.1,3189,30,3189,30
6,0400000US26,Michigan,1671899,14212,1671899,14212,89269,4444,5.3,0.3,...,75.4,0.4,51506,3374,3.1,0.2,2574,16,2574,16
7,0400000US31,Nebraska,300417,5118,300417,5118,11904,1096,4.0,0.4,...,80.4,1.0,6608,1086,2.2,0.4,2903,50,2903,50
8,0400000US41,Oregon,667980,9801,667980,9801,9873,1529,1.5,0.2,...,87.5,0.7,7658,1587,1.1,0.2,3265,36,3265,36
9,0400000US56,Wyoming,94761,4153,94761,4153,2451,741,2.6,0.8,...,43.0,2.3,1997,622,2.1,0.6,1406,33,1406,33
10,0400000US06,California,4988711,27760,4988711,27760,50607,3285,1.0,0.1,...,88.2,0.2,61965,3444,1.2,0.1,4479,28,4479,28
11,0400000US28,Mississippi,365204,8820,365204,8820,29557,3230,8.1,0.8,...,32.5,1.5,49646,3354,13.6,0.9,1225,36,1225,36
12,0400000US09,Connecticut,609456,7711,609456,7711,8749,1365,1.4,0.2,...,97.2,0.3,3067,829,0.5,0.1,5985,54,5985,54
13,0400000US48,Texas,3408366,27548,3408366,27548,114559,5801,3.4,0.2,...,83.0,0.4,100614,6012,3.0,0.2,4008,43,4008,43
14,0400000US16,Idaho,290501,8096,290501,8096,6321,1500,2.2,0.5,...,50.2,1.5,6018,1409,2.1,0.5,1538,45,1538,45
15,0400000US24,Maryland,1073634,11598,1073634,11598,19233,1927,1.8,0.2,...,89.5,0.4,15908,1920,1.5,0.2,3530,30,3530,30
16,0400000US35,New Mexico,279825,6739,279825,6739,11371,1872,4.1,0.7,...,49.3,1.7,13680,1774,4.9,0.6,1561,53,1561,53
17,0400000US01,Alabama,694367,11928,694367,11928,39762,3618,5.7,0.5,...,14.5,0.7,84904,5146,12.2,0.7,692,12,692,12
18,0400000US47,Tennessee,1010900,13314,1010900,13314,36136,2821,3.6,0.3,...,40.5,0.8,23758,2491,2.4,0.2,1319,15,1319,15
19,0400000US50,Vermont,116755,3633,116755,3633,2239,513,1.9,0.4,...,94.2,1.0,731,310,0.6,0.3,4366,97,4366,97
20,0400000US32,Nevada,435070,6717,435070,6717,7987,1385,1.8,0.3,...,55.5,1.0,10799,1609,2.5,0.4,1707,28,1707,28
21,0400000US54,West Virginia,244953,6434,244953,6434,16284,1793,6.6,0.7,...,19.3,1.4,7382,1526,3.0,0.6,870,24,870,24
22,0400000US40,Oklahoma,522069,7962,522069,7962,27544,1843,5.3,0.3,...,46.8,1.0,20689,1880,4.0,0.4,1470,22,1470,22
23,0400000US55,Wisconsin,1003101,9511,1003101,9511,24316,1885,2.4,0.2,...,90.9,0.3,6145,1105,0.6,0.1,3368,24,3368,24
24,0400000US72,Puerto Rico,302284,6695,302284,6695,5711,1305,1.9,0.4,...,3.3,0.5,245509,5911,81.2,1.1,718,47,718,47
25,0400000US20,Kansas,442557,7316,442557,7316,22002,2069,5.0,0.5,...,72.6,0.8,5982,1238,1.4,0.3,2395,32,2395,32
26,0400000US51,Virginia,1419521,14828,1419521,14828,24945,2800,1.8,0.2,...,69.4,0.5,30932,2492,2.2,0.2,2509,31,2509,31
27,0400000US38,North Dakota,106417,4386,106417,4386,4226,843,4.0,0.7,...,71.6,1.7,3222,814,3.0,0.7,2325,78,2325,78
28,0400000US34,New Jersey,1377645,12000,1377645,12000,19509,2134,1.4,0.2,...,97.8,0.2,13923,2047,1.0,0.1,8521,53,8521,53
29,0400000US39,Ohio,1924876,17146,1924876,17146,78304,3815,4.1,0.2,...,71.9,0.5,24383,2377,1.3,0.1,2518,22,2518,22
30,0400000US45,South Carolina,780604,11948,780604,11948,37309,3358,4.8,0.4,...,30.6,0.7,21288,2250,2.7,0.3,1106,17,1106,17
31,0400000US13,Georgia,1568112,21446,1568112,21446,52616,3903,3.4,0.2,...,62.6,0.7,31606,2938,2.0,0.2,1970,20,1970,20
32,0400000US08,Colorado,994356,9931,994356,9931,14187,1918,1.4,0.2,...,62.4,0.7,13166,1536,1.3,0.2,1896,22,1896,22
33,0400000US15,Hawaii,170872,5040,170872,5040,1231,484,0.7,0.3,...,55.5,1.9,8556,1208,5.0,0.7,1807,66,1807,66
34,0400000US46,South Dakota,129323,3944,129323,3944,6279,1024,4.9,0.8,...,73.1,1.8,2292,790,1.8,0.6,2350,58,2350,58
35,0400000US18,Indiana,1166290,13091,1166290,13091,52303,2983,4.5,0.2,...,39.0,0.7,28210,2386,2.4,0.2,1273,13,1273,13
36,0400000US21,Kentucky,661520,10687,661520,10687,32650,2673,4.9,0.4,...,44.8,0.9,20177,2281,3.1,0.3,1418,18,1418,18
37,0400000US22,Louisiana,593733,12573,593733,12573,26269,2801,4.4,0.5,...,31.1,1.0,87221,5215,14.7,0.8,1107,31,1107,31
38,0400000US53,Washington,1233756,12961,1233756,12961,15800,1991,1.3,0.2,...,87.1,0.5,19090,1944,1.5,0.2,3659,32,3659,32
39,0400000US17,Illinois,2002424,16877,2002424,16877,64155,2980,3.2,0.1,...,89.4,0.3,19404,1972,1.0,0.1,4900,41,4900,41
40,0400000US19,Iowa,543108,7724,543108,7724,24296,1769,4.5,0.3,...,73.8,0.8,7841,1513,1.4,0.3,2527,35,2527,35
41,0400000US33,New Hampshire,242076,6742,242076,6742,4085,999,1.7,0.4,...,95.6,0.6,1721,596,0.7,0.2,5841,75,5841,75
42,0400000US44,Rhode Island,171436,5141,171436,5141,2674,715,1.6,0.4,...,95.0,0.9,1075,538,0.6,0.3,4361,70,4361,70
43,0400000US05,Arkansas,410135,8138,410135,8138,25906,2354,6.3,0.6,...,26.1,1.1,21631,2586,5.3,0.6,935,23,935,23
44,0400000US10,Delaware,165425,4301,165425,4301,2690,805,1.6,0.5,...,53.7,1.7,3068,869,1.9,0.5,1632,45,1632,45
45,0400000US27,Minnesota,1024974,8815,1024974,8815,22770,1767,2.2,0.2,...,77.9,0.5,12982,1623,1.3,0.2,2639,22,2639,22
46,0400000US30,Montana,164197,4260,164197,4260,5016,1088,3.1,0.7,...,71.6,1.6,3086,804,1.9,0.5,2172,66,2172,66
47,0400000US04,Arizona,1072502,13375,1072502,13375,27115,2698,2.5,0.2,...,51.7,0.8,28058,2679,2.6,0.3,1591,22,1591,22
48,0400000US12,Florida,2890964,22535,2890964,22535,74152,5299,2.6,0.2,...,63.5,0.5,78236,4851,2.7,0.2,2151,25,2151,25
49,0400000US25,Massachusetts,1105499,13099,1105499,13099,10873,1351,1.0,0.1,...,94.3,0.4,6946,1013,0.6,0.1,4801,39,4801,39
50,0400000US11,District of Columbia,91179,3508,91179,3508,700,307,0.8,0.3,...,82.3,2.0,1189,415,1.3,0.5,3691,168,3691,168
51,0400000US49,Utah,491897,7432,491897,7432,9409,1618,1.9,0.3,...,63.5,1.0,9259,1418,1.9,0.3,1788,19,1788,19
52,0400000US36,New York,2366391,20282,2366391,20282,52902,3144,2.2,0.1,...,89.4,0.3,90160,5384,3.8,0.2,5837,46,5837,46

In [3]:
# List row and column counts
census_df.shape

(53, 262)

In [4]:
# List dataframe data types
census_df.dtypes

GEO_ID            object
NAME              object
S2506_C01_001E    object
S2506_C01_001M    object
S2506_C02_001E    object
                   ...
S2506_C02_064M    object
S2506_C01_065E    object
S2506_C01_065M    object
S2506_C02_065E    object
S2506_C02_065M    object
Length: 262, dtype: object

In [5]:
# Find null values
for column in census_df.columns:
    print(f"Column {column} has {census_df[column].isnull().sum()} null values")

Column GEO_ID has 0 null values
Column NAME has 0 null values
Column S2506_C01_001E has 0 null values
Column S2506_C01_001M has 0 null values
Column S2506_C02_001E has 0 null values
Column S2506_C02_001M has 0 null values
Column S2506_C01_002E has 0 null values
Column S2506_C01_002M has 0 null values
Column S2506_C02_002E has 0 null values
Column S2506_C02_002M has 0 null values
Column S2506_C01_003E has 0 null values
Column S2506_C01_003M has 0 null values
Column S2506_C02_003E has 0 null values
Column S2506_C02_003M has 0 null values
Column S2506_C01_004E has 0 null values
Column S2506_C01_004M has 0 null values
Column S2506_C02_004E has 0 null values
Column S2506_C02_004M has 0 null values
Column S2506_C01_005E has 0 null values
Column S2506_C01_005M has 0 null values
Column S2506_C02_005E has 0 null values
Column S2506_C02_005M has 0 null values
Column S2506_C01_006E has 0 null values
Column S2506_C01_006M has 0 null values
Column S2506_C02_006E has 0 null values
Column S2506_C02_006M has 0 null values
Column S2506_C01_007E has 0 null values
Column S2506_C01_007M has 0 null values
Column S2506_C02_007E has 0 null values
Column S2506_C02_007M has 0 null values
Column S2506_C01_008E has 0 null values
Column S2506_C01_008M has 0 null values
Column S2506_C02_008E has 0 null values
Column S2506_C02_008M has 0 null values
Column S2506_C01_009E has 0 null values
Column S2506_C01_009M has 0 null values
Column S2506_C02_009E has 0 null values
Column S2506_C02_009M has 0 null values
Column S2506_C01_010E has 0 null values
Column S2506_C01_010M has 0 null values
Column S2506_C02_010E has 0 null values
Column S2506_C02_010M has 0 null values
Column S2506_C01_011E has 0 null values
Column S2506_C01_011M has 0 null values
Column S2506_C02_011E has 0 null values
Column S2506_C02_011M has 0 null values
Column S2506_C01_012E has 0 null values
Column S2506_C01_012M has 0 null values
Column S2506_C02_012E has 0 null values
Column S2506_C02_012M has 0 null values
Column S2506_C01_013E has 0 null values
Column S2506_C01_013M has 0 null values
Column S2506_C02_013E has 0 null values
Column S2506_C02_013M has 0 null values
Column S2506_C01_014E has 0 null values
Column S2506_C01_014M has 0 null values
Column S2506_C02_014E has 0 null values
Column S2506_C02_014M has 0 null values
Column S2506_C01_015E has 0 null values
Column S2506_C01_015M has 0 null values
Column S2506_C02_015E has 0 null values
Column S2506_C02_015M has 0 null values
Column S2506_C01_016E has 0 null values
Column S2506_C01_016M has 0 null values
Column S2506_C02_016E has 0 null values
Column S2506_C02_016M has 0 null values
Column S2506_C01_017E has 0 null values
Column S2506_C01_017M has 0 null values
Column S2506_C02_017E has 0 null values
Column S2506_C02_017M has 0 null values
Column S2506_C01_018E has 0 null values
Column S2506_C01_018M has 0 null values
Column S2506_C02_018E has 0 null values
Column S2506_C02_018M has 0 null values
Column S2506_C01_019E has 0 null values
Column S2506_C01_019M has 0 null values
Column S2506_C02_019E has 0 null values
Column S2506_C02_019M has 0 null values
Column S2506_C01_020E has 0 null values
Column S2506_C01_020M has 0 null values
Column S2506_C02_020E has 0 null values
Column S2506_C02_020M has 0 null values
Column S2506_C01_021E has 0 null values
Column S2506_C01_021M has 0 null values
Column S2506_C02_021E has 0 null values
Column S2506_C02_021M has 0 null values
Column S2506_C01_022E has 0 null values
Column S2506_C01_022M has 0 null values
Column S2506_C02_022E has 0 null values
Column S2506_C02_022M has 0 null values
Column S2506_C01_023E has 0 null values
Column S2506_C01_023M has 0 null values
Column S2506_C02_023E has 0 null values
Column S2506_C02_023M has 0 null values
Column S2506_C01_024E has 0 null values
Column S2506_C01_024M has 0 null values
Column S2506_C02_024E has 0 null values
Column S2506_C02_024M has 0 null values
Column S2506_C01_025E has 0 null values
Column S2506_C01_025M has 0 null values
Column S2506_C02_025E has 0 null values
Column S2506_C02_025M has 0 null values
Column S2506_C01_026E has 0 null values
Column S2506_C01_026M has 0 null values
Column S2506_C02_026E has 0 null values
Column S2506_C02_026M has 0 null values
Column S2506_C01_027E has 0 null values
Column S2506_C01_027M has 0 null values
Column S2506_C02_027E has 0 null values
Column S2506_C02_027M has 0 null values
Column S2506_C01_028E has 0 null values
Column S2506_C01_028M has 0 null values
Column S2506_C02_028E has 0 null values
Column S2506_C02_028M has 0 null values
Column S2506_C01_029E has 0 null values
Column S2506_C01_029M has 0 null values
Column S2506_C02_029E has 0 null values
Column S2506_C02_029M has 0 null values
Column S2506_C01_030E has 0 null values
Column S2506_C01_030M has 0 null values
Column S2506_C02_030E has 0 null values
Column S2506_C02_030M has 0 null values
Column S2506_C01_031E has 0 null values
Column S2506_C01_031M has 0 null values
Column S2506_C02_031E has 0 null values
Column S2506_C02_031M has 0 null values
Column S2506_C01_032E has 0 null values
Column S2506_C01_032M has 0 null values
Column S2506_C02_032E has 0 null values
Column S2506_C02_032M has 0 null values
Column S2506_C01_033E has 0 null values
Column S2506_C01_033M has 0 null values
Column S2506_C02_033E has 0 null values
Column S2506_C02_033M has 0 null values
Column S2506_C01_034E has 0 null values
Column S2506_C01_034M has 0 null values
Column S2506_C02_034E has 0 null values
Column S2506_C02_034M has 0 null values
Column S2506_C01_035E has 0 null values
Column S2506_C01_035M has 0 null values
Column S2506_C02_035E has 0 null values
Column S2506_C02_035M has 0 null values
Column S2506_C01_036E has 0 null values
Column S2506_C01_036M has 0 null values
Column S2506_C02_036E has 0 null values
Column S2506_C02_036M has 0 null values
Column S2506_C01_037E has 0 null values
Column S2506_C01_037M has 0 null values
Column S2506_C02_037E has 0 null values
Column S2506_C02_037M has 0 null values
Column S2506_C01_038E has 0 null values
Column S2506_C01_038M has 0 null values
Column S2506_C02_038E has 0 null values
Column S2506_C02_038M has 0 null values
Column S2506_C01_039E has 0 null values
Column S2506_C01_039M has 0 null values
Column S2506_C02_039E has 0 null values
Column S2506_C02_039M has 0 null values
Column S2506_C01_040E has 0 null values
Column S2506_C01_040M has 0 null values
Column S2506_C02_040E has 0 null values
Column S2506_C02_040M has 0 null values
Column S2506_C01_041E has 0 null values
Column S2506_C01_041M has 0 null values
Column S2506_C02_041E has 0 null values
Column S2506_C02_041M has 0 null values
Column S2506_C01_042E has 0 null values
Column S2506_C01_042M has 0 null values
Column S2506_C02_042E has 0 null values
Column S2506_C02_042M has 0 null values
Column S2506_C01_043E has 0 null values
Column S2506_C01_043M has 0 null values
Column S2506_C02_043E has 0 null values
Column S2506_C02_043M has 0 null values
Column S2506_C01_044E has 0 null values
Column S2506_C01_044M has 0 null values
Column S2506_C02_044E has 0 null values
Column S2506_C02_044M has 0 null values
Column S2506_C01_045E has 0 null values
Column S2506_C01_045M has 0 null values
Column S2506_C02_045E has 0 null values
Column S2506_C02_045M has 0 null values
Column S2506_C01_046E has 0 null values
Column S2506_C01_046M has 0 null values
Column S2506_C02_046E has 0 null values
Column S2506_C02_046M has 0 null values
Column S2506_C01_047E has 0 null values
Column S2506_C01_047M has 0 null values
Column S2506_C02_047E has 0 null values
Column S2506_C02_047M has 0 null values
Column S2506_C01_048E has 0 null values
Column S2506_C01_048M has 0 null values
Column S2506_C02_048E has 0 null values
Column S2506_C02_048M has 0 null values
Column S2506_C01_049E has 0 null values
Column S2506_C01_049M has 0 null values
Column S2506_C02_049E has 0 null values
Column S2506_C02_049M has 0 null values
Column S2506_C01_050E has 0 null values
Column S2506_C01_050M has 0 null values
Column S2506_C02_050E has 0 null values
Column S2506_C02_050M has 0 null values
Column S2506_C01_051E has 0 null values
Column S2506_C01_051M has 0 null values
Column S2506_C02_051E has 0 null values
Column S2506_C02_051M has 0 null values
Column S2506_C01_052E has 0 null values
Column S2506_C01_052M has 0 null values
Column S2506_C02_052E has 0 null values
Column S2506_C02_052M has 0 null values
Column S2506_C01_053E has 0 null values
Column S2506_C01_053M has 0 null values
Column S2506_C02_053E has 0 null values
Column S2506_C02_053M has 0 null values
Column S2506_C01_054E has 0 null values
Column S2506_C01_054M has 0 null values
Column S2506_C02_054E has 0 null values
Column S2506_C02_054M has 0 null values
Column S2506_C01_055E has 0 null values
Column S2506_C01_055M has 0 null values
Column S2506_C02_055E has 0 null values
Column S2506_C02_055M has 0 null values
Column S2506_C01_056E has 0 null values
Column S2506_C01_056M has 0 null values
Column S2506_C02_056E has 0 null values
Column S2506_C02_056M has 0 null values
Column S2506_C01_057E has 0 null values
Column S2506_C01_057M has 0 null values
Column S2506_C02_057E has 0 null values
Column S2506_C02_057M has 0 null values
Column S2506_C01_058E has 0 null values
Column S2506_C01_058M has 0 null values
Column S2506_C02_058E has 0 null values
Column S2506_C02_058M has 0 null values
Column S2506_C01_059E has 0 null values
Column S2506_C01_059M has 0 null values
Column S2506_C02_059E has 0 null values
Column S2506_C02_059M has 0 null values
Column S2506_C01_060E has 0 null values
Column S2506_C01_060M has 0 null values
Column S2506_C02_060E has 0 null values
Column S2506_C02_060M has 0 null values
Column S2506_C01_061E has 0 null values
Column S2506_C01_061M has 0 null values
Column S2506_C02_061E has 0 null values
Column S2506_C02_061M has 0 null values
Column S2506_C01_062E has 0 null values
Column S2506_C01_062M has 0 null values
Column S2506_C02_062E has 0 null values
Column S2506_C02_062M has 0 null values
Column S2506_C01_063E has 0 null values
Column S2506_C01_063M has 0 null values
Column S2506_C02_063E has 0 null values
Column S2506_C02_063M has 0 null values
Column S2506_C01_064E has 0 null values
Column S2506_C01_064M has 0 null values
Column S2506_C02_064E has 0 null values
Column S2506_C02_064M has 0 null values
Column S2506_C01_065E has 0 null values
Column S2506_C01_065M has 0 null values
Column S2506_C02_065E has 0 null values
Column S2506_C02_065M has 0 null values

In [6]:
# Find duplicate entries
print(f"Duplicate entries: {census_df.duplicated().sum()}")

Duplicate entries: 0

In [7]:
# Only view needed column information
census = census_df.filter(items=['NAME', 'S2506_C01_002E', 'S2506_C01_003E', 'S2506_C01_004E', 'S2506_C01_005E', 'S2506_C01_006E', 'S2506_C01_007E', 'S2506_C01_008E', 'S2506_C01_009E', 'S2506_C01_010E', 'S2506_C01_011E', 'S2506_C01_012E', 'S2506_C01_013E', 'S2506_C01_014E', 'S2506_C01_015E', 'S2506_C01_016E', 'S2506_C01_017E', 'S2506_C01_018E', 'S2506_C01_019E', 'S2506_C01_020E', 'S2506_C01_021E', 'S2506_C01_022E', 'S2506_C01_023E', 'S2506_C01_042E', 'S2506_C01_068E'])
census

,NAME,S2506_C01_002E,S2506_C01_003E,S2506_C01_004E,S2506_C01_005E,S2506_C01_006E,S2506_C01_007E,S2506_C01_008E,S2506_C01_009E,S2506_C01_010E,...,S2506_C01_015E,S2506_C01_016E,S2506_C01_017E,S2506_C01_018E,S2506_C01_019E,S2506_C01_020E,S2506_C01_021E,S2506_C01_022E,S2506_C01_023E,S2506_C01_042E
0,Geographic Area Name,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...
1,Alaska,1301,2485,50283,37611,8472,1817,737,292600,7236,...,1571,4496,3062,5758,16524,15589,28377,27329,105294,52
2,Maine,8347,22503,154319,46623,10248,2816,2488,208300,37955,...,4984,14179,13658,27893,49704,45453,54975,36498,81392,10
3,North Carolina,46822,189660,943652,308264,86931,28949,19457,199600,216186,...,33345,105588,97324,184908,308772,267775,334621,291402,81504,708
4,Missouri,48211,152276,598632,135389,34108,10285,7507,170800,99005,...,18802,54355,61423,111764,192411,168477,212500,166676,81877,2162
5,Pennsylvania,69616,246255,1196823,397957,114215,29943,21342,202000,320481,...,39845,109579,100799,193505,371686,342305,478432,440000,90755,1042
6,Michigan,89269,246365,990180,257330,59518,16720,12517,175400,198116,...,31958,95718,98054,181641,326620,282044,363484,292380,83258,1756
7,Nebraska,11904,38636,195718,42879,7558,1978,1744,172500,31109,...,4293,12932,13815,26203,57362,54519,78592,52701,90685,102
8,Oregon,9873,10186,223689,272002,111089,27517,13624,355800,85717,...,8981,33678,33717,62326,117986,110124,149735,151433,91517,216
9,Wyoming,2451,3516,59858,20641,4549,2329,1417,240100,8316,...,1346,4475,4757,9579,17399,18343,24239,14623,88588,65
10,California,50607,49439,705843,1349694,1280746,673367,879015,566100,642797,...,97819,205443,184932,331404,662661,660584,1103737,1742131,113027,928
11,Mississippi,29557,77430,218413,30816,5921,1442,1625,151200,27707,...,13073,30075,26420,42396,77865,64349,65229,45797,72006,455
12,Connecticut,8749,16615,309502,173808,52081,21472,27229,281300,101080,...,8513,20988,18175,38249,86094,82289,147504,207644,114130,21
13,Texas,114559,346212,1929131,694867,206755,62007,54835,216700,167816,...,64574,171921,168145,289082,568350,517676,777430,851188,95822,1509
14,Idaho,6321,14350,170444,77776,14129,4255,3226,243800,32009,...,5546,19843,16919,35651,65905,48930,58984,38723,75554,520
15,Maryland,19233,26731,416612,384667,152620,41493,32278,331600,160428,...,14513,35644,33704,70536,139157,151785,258193,370102,115283,267
16,New Mexico,11371,23570,183221,43343,11576,3860,2884,193300,25694,...,9644,24747,21549,34438,54558,44503,53560,36826,72549,129
17,Alabama,39762,126732,408685,89306,19204,7337,3341,164200,71506,...,20689,53357,47032,74279,134010,118808,142484,103708,78432,828
18,Tennessee,36136,132105,591891,173395,48950,15943,12480,192600,95089,...,22970,68651,67070,112997,203745,171743,208503,155221,78713,803
19,Vermont,2239,5107,73229,27397,5611,1701,1471,239000,17101,...,2363,6322,6081,11677,21897,21238,29279,17898,87472,22
20,Nevada,7987,7352,200946,163053,39411,8629,7692,301100,34764,...,9498,25261,23807,45350,78201,74269,96598,82086,86294,95
21,West Virginia,16284,57029,141197,24559,4259,953,672,147100,22948,...,6655,21314,20385,32828,50951,35818,49276,27726,70059,479
22,Oklahoma,27544,100241,315832,55931,13152,4717,4652,156000,32267,...,11090,33054,31704,58164,104311,93187,110802,79757,80386,514
23,Wisconsin,24316,107410,643031,175721,35291,10230,7102,195900,157210,...,13759,49123,50101,96718,193295,183536,249068,167501,87899,219
24,Puerto Rico,5711,70384,209802,11133,3318,763,1173,130600,7176,...,24832,66621,40745,58413,56518,24139,18876,12140,39275,2287
25,Kansas,22002,76546,255657,65892,14295,5145,3020,173800,41534,...,6217,20469,23105,43937,88233,79872,99785,80939,86395,78
26,Virginia,24945,65187,613090,398126,200845,75377,41951,302700,205822,...,23783,63508,52436,107510,212825,211447,319239,428773,104322,703
27,North Dakota,4226,8007,65160,21611,5111,1850,452,226000,10446,...,1215,2464,3613,7989,19480,20099,31106,20451,97677,24
28,New Jersey,19509,24607,491808,482681,227541,77787,53712,352700,192181,...,19381,44930,43258,77830,169025,177942,325299,519980,121642,0
29,Ohio,78304,360433,1176833,236677,51676,12430,8523,160800,280049,...,35384,107602,110962,206283,371517,336065,434287,322776,83629,1375
30,South Carolina,37309,94765,455433,129503,41955,11002,10637,194100,78529,...,20450,56030,55345,86275,157607,128904,151315,124678,77141,418
31,Georgia,52616,163318,898937,306655,97191,27667,21728,208800,152359,...,41903,89731,87352,149405,276299,245262,338840,339320,88772,896
32,Colorado,14187,17630,272153,413877,184283,56966,35260,383400,128957,...,17931,37319,42818,77456,155216,157165,239397,267054,101056,245
33,Hawaii,1231,1559,13205,38659,53766,34790,27662,643100,33084,...,3585,4148,5680,12052,22435,22830,44608,55534,113390,18
34,South Dakota,6279,14192,81910,21037,4135,1021,749,188800,12380,...,1017,4462,7482,14481,25568,30367,29911,16035,83662,169
35,Indiana,52303,234396,710148,127502,28818,8034,5089,153800,135897,...,22006,75032,75098,133027,242161,213587,248477,156902,78796,1182
36,Kentucky,32650,112746,406313,81113,19345,5451,3902,162800,90322,...,17620,46048,47644,76589,130771,110699,139515,92634,77340,1805
37,Louisiana,26269,70644,376052,90015,19935,5601,5217,184900,47413,...,15942,45791,39014,58396,105943,96938,130202,101507,81863,755
38,Washington,15800,17276,367879,433752,212109,105414,81526,385000,150758,...,18257,44341,44737,92770,187307,191182,299783,355379,104432,397
39,Illinois,64155,233333,1081655,409749,131301,41771,40460,219400,241192,...,35155,94058,95658,168952,335047,308080,461509,503965,96714,600
40,Iowa,24296,102701,328142,71618,12222,2396,1733,160700,70190,...,8299,29059,30585,55628,107330,103098,127569,81540,83998,286
41,New Hampshire,4085,6493,126744,80736,16962,4012,3044,278600,33029,...,3260,8036,10524,16028,34817,38661,66400,64350,105339,56
42,Rhode Island,2674,2961,94557,52966,11111,3930,3237,274200,26371,...,2071,7282,8060,13202,28907,27619,43220,41075,98266,0
43,Arkansas,25906,88898,238302,42065,7997,3907,3060,148300,27382,...,11784,33638,30367,51783,81975,62311,81585,56692,73522,1139
44,Delaware,2690,4764,90290,53229,8937,3016,2499,267000,20473,...,3920,10195,8002,14651,32016,25841,37210,33590,87168,89
45,Minnesota,22770,54159,597100,256265,66479,17073,11128,244800,149130,...,13278,36475,40723,87675,166252,175149,264182,241240,98831,383
46,Montana,5016,7376,86860,44075,14127,3709,3034,262400,15917,...,3000,10860,9456,19087,35936,29008,33197,23653,77282,76
47,Arizona,27115,43691,598719,280745,79458,23128,19646,256600,100670,...,24645,63580,59040,111112,204448,175012,227398,207267,84628,919
48,Florida,74152,185507,1591788,710945,197240,65247,66085,247000,303356,...,81690,209722,184353,324338,536246,450785,572584,531246,80372,1990
49,Massachusetts,10873,8759,294869,400054,237561,82421,70962,406900,199591,...,14336,34772,34321,60659,143466,143753,261353,412839,121565,92
50,District of Columbia,700,552,8147,24676,22666,16753,17685,627000,14236,...,1981,2580,1761,2662,8230,9267,18518,46180,151147,0
51,Utah,9409,5888,218789,184533,50940,13839,8499,310000,72368,...,5152,18318,21123,39651,93726,89817,129122,94988,93060,222
52,New York,52902,188708,818165,563394,376377,177251,189594,341900,325392,...,39767,99223,91966,161036,338765,336915,551156,747563,108546,1205

In [8]:
# Change column names
census.rename(columns={'NAME': 'State', 'S2506_C01_002E': 'Home Value <$50k (%)', 'S2506_C01_003E': 'Home Value $50k-$90k (%)', 'S2506_C01_004E': 'Home Value $100k-$149k (%)', 'S2506_C01_005E': 'Home Value $150k-$199k (%)', 'S2506_C01_006E': 'Home Value $200k-$299k (%)', 'S2506_C01_007E': 'Home Value $300k-$499k (%)', 'S2506_C01_008E': 'Home Value $500k+ (%)', 'S2506_C01_009E':'Median Home Value ($)(1000X)', 'S2506_C01_010E': '2nd Mortgage or Equity Loan (%)', 'S2506_C01_011E': '2nd Mortgage Only (%)', 'S2506_C01_012E': 'Equity Loan Only (%)', 'S2506_C01_013E': 'Both 2nd & Equity Loan (%)', 'S2506_C01_014E': 'No 2nd or Equity Loan (%)', 'S2506_C01_015E': 'Income <$10k (%)', 'S2506_C01_016E': 'Income $10k-$24,999 (%)', 'S2506_C01_017E': 'Income $25k-$34,999 (%)', 'S2506_C01_018E': 'Income $35k-$49,999 (%)', 'S2506_C01_019E': 'Income $50k-$74,999 (%)', 'S2506_C01_020E': 'Income $75k-$99,999 (%)', 'S2506_C01_021E': 'Income $100k-$149,999 (%)', 'S2506_C01_022E': 'Income $150k+ (%)', 'S2506_C01_023E': 'Median Income ($)(1000X)', 'S2506_C01_042E': 'Median Housing Cost (monthly) ($)', 'S2506_C01_068E': 'Median Real Estate Taxes ($)'}, inplace=True)
census.head()

,State,Home Value <$50k (%),Home Value $50k-$90k (%),Home Value $100k-$149k (%),Home Value $150k-$199k (%),Home Value $200k-$299k (%),Home Value $300k-$499k (%),Home Value $500k+ (%),Median Home Value ($)(1000X),2nd Mortgage or Equity Loan (%),...,Income <$10k (%),"Income $10k-$24,999 (%)","Income $25k-$34,999 (%)","Income $35k-$49,999 (%)","Income $50k-$74,999 (%)","Income $75k-$99,999 (%)","Income $100k-$149,999 (%)",Income $150k+ (%),Median Income ($)(1000X),Median Housing Cost (monthly) ($)
0,Geographic Area Name,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...
1,Alaska,1301,2485,50283,37611,8472,1817,737,292600,7236,...,1571,4496,3062,5758,16524,15589,28377,27329,105294,52
2,Maine,8347,22503,154319,46623,10248,2816,2488,208300,37955,...,4984,14179,13658,27893,49704,45453,54975,36498,81392,10
3,North Carolina,46822,189660,943652,308264,86931,28949,19457,199600,216186,...,33345,105588,97324,184908,308772,267775,334621,291402,81504,708
4,Missouri,48211,152276,598632,135389,34108,10285,7507,170800,99005,...,18802,54355,61423,111764,192411,168477,212500,166676,81877,2162

In [9]:
# Adding 'Year' column
census.insert(0, 'Year', 2018)
census.head()

,Year,State,Home Value <$50k (%),Home Value $50k-$90k (%),Home Value $100k-$149k (%),Home Value $150k-$199k (%),Home Value $200k-$299k (%),Home Value $300k-$499k (%),Home Value $500k+ (%),Median Home Value ($)(1000X),...,Income <$10k (%),"Income $10k-$24,999 (%)","Income $25k-$34,999 (%)","Income $35k-$49,999 (%)","Income $50k-$74,999 (%)","Income $75k-$99,999 (%)","Income $100k-$149,999 (%)",Income $150k+ (%),Median Income ($)(1000X),Median Housing Cost (monthly) ($)
0,2018,Geographic Area Name,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...,Estimate!!Owner-occupied housing units with a ...
1,2018,Alaska,1301,2485,50283,37611,8472,1817,737,292600,...,1571,4496,3062,5758,16524,15589,28377,27329,105294,52
2,2018,Maine,8347,22503,154319,46623,10248,2816,2488,208300,...,4984,14179,13658,27893,49704,45453,54975,36498,81392,10
3,2018,North Carolina,46822,189660,943652,308264,86931,28949,19457,199600,...,33345,105588,97324,184908,308772,267775,334621,291402,81504,708
4,2018,Missouri,48211,152276,598632,135389,34108,10285,7507,170800,...,18802,54355,61423,111764,192411,168477,212500,166676,81877,2162

In [10]:
# Delete rows with index 0    
census = census.drop([0])

In [11]:
census.head()

,Year,State,Home Value <$50k (%),Home Value $50k-$90k (%),Home Value $100k-$149k (%),Home Value $150k-$199k (%),Home Value $200k-$299k (%),Home Value $300k-$499k (%),Home Value $500k+ (%),Median Home Value ($)(1000X),...,Income <$10k (%),"Income $10k-$24,999 (%)","Income $25k-$34,999 (%)","Income $35k-$49,999 (%)","Income $50k-$74,999 (%)","Income $75k-$99,999 (%)","Income $100k-$149,999 (%)",Income $150k+ (%),Median Income ($)(1000X),Median Housing Cost (monthly) ($)
1,2018,Alaska,1301,2485,50283,37611,8472,1817,737,292600,...,1571,4496,3062,5758,16524,15589,28377,27329,105294,52
2,2018,Maine,8347,22503,154319,46623,10248,2816,2488,208300,...,4984,14179,13658,27893,49704,45453,54975,36498,81392,10
3,2018,North Carolina,46822,189660,943652,308264,86931,28949,19457,199600,...,33345,105588,97324,184908,308772,267775,334621,291402,81504,708
4,2018,Missouri,48211,152276,598632,135389,34108,10285,7507,170800,...,18802,54355,61423,111764,192411,168477,212500,166676,81877,2162
5,2018,Pennsylvania,69616,246255,1196823,397957,114215,29943,21342,202000,...,39845,109579,100799,193505,371686,342305,478432,440000,90755,1042

In [12]:
# Is the data in a format that can be passed into an unsupervised learning model?
census.dtypes

Year                                  int64
State                                object
Home Value <$50k (%)                 object
Home Value $50k-$90k (%)             object
Home Value $100k-$149k (%)           object
Home Value $150k-$199k (%)           object
Home Value $200k-$299k (%)           object
Home Value $300k-$499k (%)           object
Home Value $500k+ (%)                object
Median Home Value ($)(1000X)         object
2nd Mortgage or Equity Loan (%)      object
2nd Mortgage Only (%)                object
Equity Loan Only (%)                 object
Both 2nd & Equity Loan (%)           object
No 2nd or Equity Loan (%)            object
Income <$10k (%)                     object
Income $10k-$24,999 (%)              object
Income $25k-$34,999 (%)              object
Income $35k-$49,999 (%)              object
Income $50k-$74,999 (%)              object
Income $75k-$99,999 (%)              object
Income $100k-$149,999 (%)            object
Income $150k+ (%)                    object
Median Income ($)(1000X)             object
Median Housing Cost (monthly) ($)    object
dtype: object

In [13]:
# Temporarily delete State column to convert entire df to numeric
del census['State']

In [14]:
# Convert entire df to numeric
census = census.apply(pd.to_numeric)

In [15]:
# Make sure all dtypes are numeric
census.dtypes

Year                                 int64
Home Value <$50k (%)                 int64
Home Value $50k-$90k (%)             int64
Home Value $100k-$149k (%)           int64
Home Value $150k-$199k (%)           int64
Home Value $200k-$299k (%)           int64
Home Value $300k-$499k (%)           int64
Home Value $500k+ (%)                int64
Median Home Value ($)(1000X)         int64
2nd Mortgage or Equity Loan (%)      int64
2nd Mortgage Only (%)                int64
Equity Loan Only (%)                 int64
Both 2nd & Equity Loan (%)           int64
No 2nd or Equity Loan (%)            int64
Income <$10k (%)                     int64
Income $10k-$24,999 (%)              int64
Income $25k-$34,999 (%)              int64
Income $35k-$49,999 (%)              int64
Income $50k-$74,999 (%)              int64
Income $75k-$99,999 (%)              int64
Income $100k-$149,999 (%)            int64
Income $150k+ (%)                    int64
Median Income ($)(1000X)             int64
Median Housing Cost (monthly) ($)    int64
dtype: object

In [16]:
# Return the State column
census.insert(1, 'State', census_df['NAME'])
census.head()

,Year,State,Home Value <$50k (%),Home Value $50k-$90k (%),Home Value $100k-$149k (%),Home Value $150k-$199k (%),Home Value $200k-$299k (%),Home Value $300k-$499k (%),Home Value $500k+ (%),Median Home Value ($)(1000X),...,Income <$10k (%),"Income $10k-$24,999 (%)","Income $25k-$34,999 (%)","Income $35k-$49,999 (%)","Income $50k-$74,999 (%)","Income $75k-$99,999 (%)","Income $100k-$149,999 (%)",Income $150k+ (%),Median Income ($)(1000X),Median Housing Cost (monthly) ($)
1,2018,Alaska,1301,2485,50283,37611,8472,1817,737,292600,...,1571,4496,3062,5758,16524,15589,28377,27329,105294,52
2,2018,Maine,8347,22503,154319,46623,10248,2816,2488,208300,...,4984,14179,13658,27893,49704,45453,54975,36498,81392,10
3,2018,North Carolina,46822,189660,943652,308264,86931,28949,19457,199600,...,33345,105588,97324,184908,308772,267775,334621,291402,81504,708
4,2018,Missouri,48211,152276,598632,135389,34108,10285,7507,170800,...,18802,54355,61423,111764,192411,168477,212500,166676,81877,2162
5,2018,Pennsylvania,69616,246255,1196823,397957,114215,29943,21342,202000,...,39845,109579,100799,193505,371686,342305,478432,440000,90755,1042

In [17]:
# The scale for Median Home Value is much larger than all the other values in the dataset
census['Median Home Value ($)(1000X)'] = census['Median Home Value ($)(1000X)'].div(1000)

In [18]:
# The scale for Median Income is much larger than all the other values in the dataset
census['Median Income ($)(1000X)'] = census['Median Income ($)(1000X)'].div(1000)

In [19]:
census

,Year,State,Home Value <$50k (%),Home Value $50k-$90k (%),Home Value $100k-$149k (%),Home Value $150k-$199k (%),Home Value $200k-$299k (%),Home Value $300k-$499k (%),Home Value $500k+ (%),Median Home Value ($)(1000X),...,Income <$10k (%),"Income $10k-$24,999 (%)","Income $25k-$34,999 (%)","Income $35k-$49,999 (%)","Income $50k-$74,999 (%)","Income $75k-$99,999 (%)","Income $100k-$149,999 (%)",Income $150k+ (%),Median Income ($)(1000X),Median Housing Cost (monthly) ($)
1,2018,Alaska,1301,2485,50283,37611,8472,1817,737,292.6,...,1571,4496,3062,5758,16524,15589,28377,27329,105.294,52
2,2018,Maine,8347,22503,154319,46623,10248,2816,2488,208.3,...,4984,14179,13658,27893,49704,45453,54975,36498,81.392,10
3,2018,North Carolina,46822,189660,943652,308264,86931,28949,19457,199.6,...,33345,105588,97324,184908,308772,267775,334621,291402,81.504,708
4,2018,Missouri,48211,152276,598632,135389,34108,10285,7507,170.8,...,18802,54355,61423,111764,192411,168477,212500,166676,81.877,2162
5,2018,Pennsylvania,69616,246255,1196823,397957,114215,29943,21342,202.0,...,39845,109579,100799,193505,371686,342305,478432,440000,90.755,1042
6,2018,Michigan,89269,246365,990180,257330,59518,16720,12517,175.4,...,31958,95718,98054,181641,326620,282044,363484,292380,83.258,1756
7,2018,Nebraska,11904,38636,195718,42879,7558,1978,1744,172.5,...,4293,12932,13815,26203,57362,54519,78592,52701,90.685,102
8,2018,Oregon,9873,10186,223689,272002,111089,27517,13624,355.8,...,8981,33678,33717,62326,117986,110124,149735,151433,91.517,216
9,2018,Wyoming,2451,3516,59858,20641,4549,2329,1417,240.1,...,1346,4475,4757,9579,17399,18343,24239,14623,88.588,65
10,2018,California,50607,49439,705843,1349694,1280746,673367,879015,566.1,...,97819,205443,184932,331404,662661,660584,1103737,1742131,113.027,928
11,2018,Mississippi,29557,77430,218413,30816,5921,1442,1625,151.2,...,13073,30075,26420,42396,77865,64349,65229,45797,72.006,455
12,2018,Connecticut,8749,16615,309502,173808,52081,21472,27229,281.3,...,8513,20988,18175,38249,86094,82289,147504,207644,114.130,21
13,2018,Texas,114559,346212,1929131,694867,206755,62007,54835,216.7,...,64574,171921,168145,289082,568350,517676,777430,851188,95.822,1509
14,2018,Idaho,6321,14350,170444,77776,14129,4255,3226,243.8,...,5546,19843,16919,35651,65905,48930,58984,38723,75.554,520
15,2018,Maryland,19233,26731,416612,384667,152620,41493,32278,331.6,...,14513,35644,33704,70536,139157,151785,258193,370102,115.283,267
16,2018,New Mexico,11371,23570,183221,43343,11576,3860,2884,193.3,...,9644,24747,21549,34438,54558,44503,53560,36826,72.549,129
17,2018,Alabama,39762,126732,408685,89306,19204,7337,3341,164.2,...,20689,53357,47032,74279,134010,118808,142484,103708,78.432,828
18,2018,Tennessee,36136,132105,591891,173395,48950,15943,12480,192.6,...,22970,68651,67070,112997,203745,171743,208503,155221,78.713,803
19,2018,Vermont,2239,5107,73229,27397,5611,1701,1471,239.0,...,2363,6322,6081,11677,21897,21238,29279,17898,87.472,22
20,2018,Nevada,7987,7352,200946,163053,39411,8629,7692,301.1,...,9498,25261,23807,45350,78201,74269,96598,82086,86.294,95
21,2018,West Virginia,16284,57029,141197,24559,4259,953,672,147.1,...,6655,21314,20385,32828,50951,35818,49276,27726,70.059,479
22,2018,Oklahoma,27544,100241,315832,55931,13152,4717,4652,156.0,...,11090,33054,31704,58164,104311,93187,110802,79757,80.386,514
23,2018,Wisconsin,24316,107410,643031,175721,35291,10230,7102,195.9,...,13759,49123,50101,96718,193295,183536,249068,167501,87.899,219
24,2018,Puerto Rico,5711,70384,209802,11133,3318,763,1173,130.6,...,24832,66621,40745,58413,56518,24139,18876,12140,39.275,2287
25,2018,Kansas,22002,76546,255657,65892,14295,5145,3020,173.8,...,6217,20469,23105,43937,88233,79872,99785,80939,86.395,78
26,2018,Virginia,24945,65187,613090,398126,200845,75377,41951,302.7,...,23783,63508,52436,107510,212825,211447,319239,428773,104.322,703
27,2018,North Dakota,4226,8007,65160,21611,5111,1850,452,226.0,...,1215,2464,3613,7989,19480,20099,31106,20451,97.677,24
28,2018,New Jersey,19509,24607,491808,482681,227541,77787,53712,352.7,...,19381,44930,43258,77830,169025,177942,325299,519980,121.642,0
29,2018,Ohio,78304,360433,1176833,236677,51676,12430,8523,160.8,...,35384,107602,110962,206283,371517,336065,434287,322776,83.629,1375
30,2018,South Carolina,37309,94765,455433,129503,41955,11002,10637,194.1,...,20450,56030,55345,86275,157607,128904,151315,124678,77.141,418
31,2018,Georgia,52616,163318,898937,306655,97191,27667,21728,208.8,...,41903,89731,87352,149405,276299,245262,338840,339320,88.772,896
32,2018,Colorado,14187,17630,272153,413877,184283,56966,35260,383.4,...,17931,37319,42818,77456,155216,157165,239397,267054,101.056,245
33,2018,Hawaii,1231,1559,13205,38659,53766,34790,27662,643.1,...,3585,4148,5680,12052,22435,22830,44608,55534,113.390,18
34,2018,South Dakota,6279,14192,81910,21037,4135,1021,749,188.8,...,1017,4462,7482,14481,25568,30367,29911,16035,83.662,169
35,2018,Indiana,52303,234396,710148,127502,28818,8034,5089,153.8,...,22006,75032,75098,133027,242161,213587,248477,156902,78.796,1182
36,2018,Kentucky,32650,112746,406313,81113,19345,5451,3902,162.8,...,17620,46048,47644,76589,130771,110699,139515,92634,77.340,1805
37,2018,Louisiana,26269,70644,376052,90015,19935,5601,5217,184.9,...,15942,45791,39014,58396,105943,96938,130202,101507,81.863,755
38,2018,Washington,15800,17276,367879,433752,212109,105414,81526,385.0,...,18257,44341,44737,92770,187307,191182,299783,355379,104.432,397
39,2018,Illinois,64155,233333,1081655,409749,131301,41771,40460,219.4,...,35155,94058,95658,168952,335047,308080,461509,503965,96.714,600
40,2018,Iowa,24296,102701,328142,71618,12222,2396,1733,160.7,...,8299,29059,30585,55628,107330,103098,127569,81540,83.998,286
41,2018,New Hampshire,4085,6493,126744,80736,16962,4012,3044,278.6,...,3260,8036,10524,16028,34817,38661,66400,64350,105.339,56
42,2018,Rhode Island,2674,2961,94557,52966,11111,3930,3237,274.2,...,2071,7282,8060,13202,28907,27619,43220,41075,98.266,0
43,2018,Arkansas,25906,88898,238302,42065,7997,3907,3060,148.3,...,11784,33638,30367,51783,81975,62311,81585,56692,73.522,1139
44,2018,Delaware,2690,4764,90290,53229,8937,3016,2499,267.0,...,3920,10195,8002,14651,32016,25841,37210,33590,87.168,89
45,2018,Minnesota,22770,54159,597100,256265,66479,17073,11128,244.8,...,13278,36475,40723,87675,166252,175149,264182,241240,98.831,383
46,2018,Montana,5016,7376,86860,44075,14127,3709,3034,262.4,...,3000,10860,9456,19087,35936,29008,33197,23653,77.282,76
47,2018,Arizona,27115,43691,598719,280745,79458,23128,19646,256.6,...,24645,63580,59040,111112,204448,175012,227398,207267,84.628,919
48,2018,Florida,74152,185507,1591788,710945,197240,65247,66085,247.0,...,81690,209722,184353,324338,536246,450785,572584,531246,80.372,1990
49,2018,Massachusetts,10873,8759,294869,400054,237561,82421,70962,406.9,...,14336,34772,34321,60659,143466,143753,261353,412839,121.565,92
50,2018,District of Columbia,700,552,8147,24676,22666,16753,17685,627.0,...,1981,2580,1761,2662,8230,9267,18518,46180,151.147,0
51,2018,Utah,9409,5888,218789,184533,50940,13839,8499,310.0,...,5152,18318,21123,39651,93726,89817,129122,94988,93.060,222
52,2018,New York,52902,188708,818165,563394,376377,177251,189594,341.9,...,39767,99223,91966,161036,338765,336915,551156,747563,108.546,1205

In [20]:
# Saving cleaned data
file_path = "../Resources/clean_data/Cost/census_2018.csv"
census.to_csv(file_path, index=False)